import Header from "@/components/Header";
import MobileHeader from "@/components/MobileHeader";
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
const kyivSans = localFont({
  src: [
    {
      path: "./fonts/KyivTypeSansBold.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/KyivTypeSansMedium.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-kyiv-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["400", "500", "600", "700", "800", "900", "200"],
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${fontSans.variable} ${kyivSans.variable} font-sans  antialiased`}
      >
        <Header />
        <MobileHeader />
        {children}
      </body>
    </html>
  );
}
