import Header from "@/components/Header";
import MobileHeader from "@/components/MobileHeader";
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
const kyivSans = localFont({
  src: [
    {
      path: "./fonts/KyivTypeSansBold.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/KyivTypeSansMedium.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-kyiv-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["400", "500", "600", "700", "800", "900", "200"],
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/favicon/apple-touch-icon.png"
        />
        <link
          rel="android-chrome"
          sizes="512x512"
          href="/favicon/android-chrome-512x512.png"
        />
        <link
          rel="android-chrome"
          sizes="512x512"
          href="/favicon/android-chrome-512x512.png"
        />
        <link
          rel="android-chrome"
          sizes="180x180"
          href="/favicon/android-chrome-512x512.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon/favicon-16x16.png"
        />
        <link rel="manifest" href="/favicon/site.webmanifest" />
        <link
          rel="mask-icon"
          href="/favicon/safari-pinned-tab.svg"
          color="#5bbad5"
        />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff" />
      </head>
      <body
        className={`${fontSans.variable} ${kyivSans.variable} font-sans  antialiased`}
      >
        <Header />
        <MobileHeader />
        {children}
      </body>
    </html>
  );
}
